owner: culturecloud
repo: status
user-agent: culturecloud

sites:
  - name: Official Blog
    url: https://culturecloud.eu.org
  - name: Official Status Page
    url: https://status.culturecloud.eu.org
  - name: Telegram DDL Service
    url: $TG_DDL_SERVICE
    maxResponseTime: 60000
  - name: OneDrive DDL Service
    url: $OD_DDL_SERVICE_1
  - name: OneDrive DDL Service 2
    url: $OD_DDL_SERVICE_2
  - name: GDrive DDL Service
    url: $GD_DDL_SERVICE
  - name: Multi Cloud (Rclone) DDL Service
    url: $RC_DDL_SERVICE
    headers:
      - "authorization: Basic $BASIC_AUTH_TOKEN"
  - name: Image Proxy Service
    url: $IMAGE_PROXY_SERVICE
  - name: Pixiv Frontend
    url: https://pixiv.culturecloud.eu.org
  - name: Web Monitoring Service ⚡
    url: https://monitor.culturecloud.eu.org/api/v1/systeminfo
    headers:
      - "x-api-key: $API_KEY_WEB_MONITORING_SERVICE"
    maxResponseTime: 60000
  - name: Filebrowser ⚡ (iafuad)
    url: $FILEBROWSER_LITNG_IAFUAD
    maxResponseTime: 60000
  - name: Filebrowser ⚡ (pseudo-kawaii)
    url: $FILEBROWSER_LITNG_PSEUDO_KAWAII
    maxResponseTime: 60000
  - name: qBittorrent ⚡
    url: https://qbt.culturecloud.eu.org
  - name: Jackett ⚡
    url: https://jackett.culturecloud.eu.org
  - name: Duplicati ⚡
    url: https://duplicati.culturecloud.eu.org
  
workflowSchedule:
  uptime: "*/5 * * * *"

status-website:
  theme: dark
  cname: status.culturecloud.eu.org
  favicon: https://cdn.jsdelivr.net/gh/culturecloud/static-resources/images/favicon.ico
  logoUrl: https://cdn.jsdelivr.net/gh/culturecloud/static-resources/images/culturecloud.webp
  name: Culture Cloud
  # introTitle: "Cultured Projects for Cultured People"
  introMessage: "This is the status page for various projects we're messing around with. You can contact us at [contact@culturecloud.eu.org](mailto:contact@culturecloud.eu.org)."
  navbar:
    - title: Blog
      href: https://culturecloud.eu.org
    - title: GitHub
      href: https://github.com/$OWNER

