# Change these first
owner: culturecloud # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Blog Site
    url: https://culturecloud.gq
  - name: Mega Index
    url: https://index.culturecloud.gq
    headers:
      - "Authorization: Basic $AUTH"
  - name: Tachidesk Server
    url: https://tachidesk.culturecloud.gq
    headers:
      - "Authorization: Basic $AUTH"
  - name: DDL Service
    url: https://dl.culturecloud.gq

status-website:
  theme: dark
  cname: status.culturecloud.gq
  favicon: https://cdn.jsdelivr.net/gh/culturecloud/static-resources/images/favicon.ico
  logoUrl: https://cdn.jsdelivr.net/gh/culturecloud/static-resources/images/culturecloud.webp
  name: Culture Cloud
  # introTitle: ""
  # introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
