# Change these first
owner: culturecloud # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: streamgram-bot
    url: https://streamgram-bot.culturecloud.repl.co
    merhod: GET

status-website:
  theme: dark
  cname: status.culturecloud.gq
  favicon: https://cdn.jsdelivr.net/gh/culturecloud/static-resources/images/favicon.ico
  logoUrl: https://cdn.jsdelivr.net/gh/culturecloud/static-resources/images/culturecloud.webp
  name: Culture Cloud
  # introTitle: ""
  # introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

commitMessages:
  commitAuthorName: "Culture Cloud"
  commitAuthorEmail: "admin@culturecloud.gq"

user-agent: culturecloud
