owner: culturecloud
repo: status
user-agent: culturecloud

sites:
  - name: Official Blog
    url: https://culturecloud.eu.org
  - name: Official Status Page
    url: https://status.culturecloud.eu.org
  - name: Telegram DDL Service
    url: $TG_DDL_SERVICE
  - name: OneDrive DDL Service
    url: $OD_DDL_INDEX
  - name: GDrive DDL Service
    url: $GD_DDL_SERVICE
  - name: Rclone DDL Service
    url: $RC_DDL_SERVICE
    headers:
      - "Authorization: Basic $BASIC_AUTH_TOKEN"
  - name: Image Proxy Service
    url: $IMAGE_PROXY_SERVICE
  - name: Web Monitoring Service
    url: $WEB_MONITORING_SERVICE
  - name: Freenom Renewal Service
    url: $FREENOM_RENEWAL_SERVICE
  - name: Rendered Bless Service
    url: $RENDERED_BLESS_SERVICE
    
workflowSchedule:
  uptime: "*/5 * * * *"

status-website:
  theme: dark
  cname: status.culturecloud.eu.org
  favicon: https://cdn.jsdelivr.net/gh/culturecloud/static-resources/images/favicon.ico
  logoUrl: https://cdn.jsdelivr.net/gh/culturecloud/static-resources/images/culturecloud.webp
  name: Culture Cloud
  # introTitle: "Cultured Projects for Cultured People"
  introMessage: "This is the status page for various projects we're messing around with. You can contact us at [contact@culturecloud.eu.org](mailto:contact@culturecloud.eu.org)."
  navbar:
    - title: Blog
      href: https://culturecloud.eu.org
    - title: GitHub
      href: https://github.com/$OWNER

