owner: culturecloud
repo: status
user-agent: culturecloud

sites:
  - name: Culture Cloud Blog
    url: https://culturecloud.gq
    maxResponseTime: 5000
  - name: Personal Journal
    url: https://journal.culturecloud.gq
    maxResponseTime: 5000
  - name: DDL Service
    url: https://dl.culturecloud.gq
    maxResponseTime: 5000
  - name: Telegram Index
    url: https://tgdex.culturecloud.gq
    maxResponseTime: 5000
    
workflowSchedule:
  uptime: "*/15 * * * *"

status-website:
  theme: dark
  cname: status.culturecloud.gq
  favicon: https://cdn.jsdelivr.net/gh/culturecloud/static-resources/images/favicon.ico
  logoUrl: https://cdn.jsdelivr.net/gh/culturecloud/static-resources/images/culturecloud.webp
  name: Culture Cloud
  # introTitle: ""
  introMessage: "This is the status page for various projects we're messing around with. You can contact us at [culturecloud@duck.com](mailto:culturecloud@duck.com)."
  navbar:
    - title: Blog
      href: https://culturecloud.gq
    - title: GitHub
      href: https://github.com/$OWNER

