owner: culturecloud
repo: status

sites:
  - name: Blog Site
    url: https://culturecloud.gq
    maxResponseTime: 5000
  - name: Journal
    url: https://journal.culturecloud.gq
    maxResponseTime: 5000
  - name: Mega Index
    url: https://index.culturecloud.gq
    headers:
      - "Authorization: Basic $AUTH"
    maxResponseTime: 5000
  - name: Tachidesk Server
    url: https://tachidesk.culturecloud.gq
    headers:
      - "Authorization: Basic $AUTH"
    maxResponseTime: 5000
  - name: DDL Service
    url: https://dl.culturecloud.gq
    maxResponseTime: 5000

status-website:
  theme: dark
  cname: status.culturecloud.gq
  favicon: https://cdn.jsdelivr.net/gh/culturecloud/static-resources/images/favicon.ico
  logoUrl: https://cdn.jsdelivr.net/gh/culturecloud/static-resources/images/culturecloud.webp
  name: Culture Cloud
  # introTitle: ""
  # introMessage: ""
