owner: culturecloud
repo: status
user-agent: culturecloud

sites:
  - name: Culture Cloud Blog
    url: https://culturecloud.gq
    maxResponseTime: 5000
  - name: Journal
    url: https://journal.culturecloud.gq
    maxResponseTime: 5000
  - name: Drive Index
    url: https://drive.culturecloud.gq
    maxResponseTime: 5000
    headers:
      - "Authorization: Basic $AUTH"
  - name: Tachidesk Server
    url: https://tachidesk.culturecloud.gq
    maxResponseTime: 5000
    headers:
      - "Authorization: Basic $AUTH"
  - name: DDL Service
    url: https://dl.culturecloud.gq
    maxResponseTime: 5000
  - name: Telegram Index
    url: https://tgdex.culturecloud.gq
    maxResponseTime: 5000
    
workflowSchedule:
  uptime: "*/5 * * * *"

status-website:
  theme: dark
  cname: status.culturecloud.gq
  favicon: https://cdn.jsdelivr.net/gh/culturecloud/static-resources/images/favicon.ico
  logoUrl: https://cdn.jsdelivr.net/gh/culturecloud/static-resources/images/culturecloud.webp
  name: Culture Cloud
  # introTitle: ""
  introMessage: "This is the status page for various projects we'll be working on. You can contact us at [culturecloud@protonmail.com](mailto:culturecloud@protonmail.com)."
  navbar:
    - title: Blog
      href: https://culturecloud.gq
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

